CIAB/Controllers/ChangePasswordController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using CIAB.Models;
using CIAB.DataLayer;

namespace CIAB.Controllers
{
    public class ChangePasswordController : BaseController
    {
        #region Methods
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ChangeUserPassword()
        {
            if (Convert.ToString(Session["UserName"]).ToLower() == null || Convert.ToString(Session["UserName"]).ToLower() == string.Empty)
            {
                return RedirectToAction("SignUpLogin", "Home");
            }

            return View();
        }
        [HttpPost]
        public ActionResult ChangeUserPassword(ResetPassword ResetPass)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string strCurrentPass = GetSHA1(ResetPass.CurrentPass + "d3katk00");
                    string strNewPass = GetSHA1(ResetPass.NewPass + "d3katk00");
                    string strOldPassword = "";
                    if (HttpContext.Session["Password"] != null)
                    {
                        strOldPassword = HttpContext.Session["Password"].ToString();
                        if (strCurrentPass != strOldPassword)
                        {
                            ViewBag.ErrorMessage = "Current Password is not Valid!";
                            return View("ChangeUserPassword");
                        }
                        else if (strOldPassword == strNewPass)
                        {
                            ViewBag.Error = "New password cannot be the same as old password";
                            return View("ChangeUserPassword");
                        }
                    }
                    //check if old password and new hashed password resembles.
                    int returnValue = AddNewPassword(ResetPass, strCurrentPass, strNewPass);
                    if (returnValue == 1)
                    {
                        return RedirectToAction("PasswordResetSuccess");
                    }
                    else
                    {
                        return View(ResetPass);
                    }
                }
                else
                {
                    ModelState.AddModelError("resetpass", "Process failed.");
                    return View("ChangeUserPassword", ResetPass);
                }
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "ChangeUserPassword_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
                ModelState.AddModelError("resetpass", "Process failed.");
                return View("ChangeUserPassword", ResetPass);
            }
        }
        public ViewResult PasswordResetSuccess()
        {
            return View();
        }
        private int AddNewPassword(ResetPassword ResetPass, string strCurrentPass, string strNewPass)
        {
            if (HttpContext.Session["UserName"] != null)
            {
                ResetPass.UserName = HttpContext.Session["UserName"].ToString();
            }
            ChangePasswordDataLayer changepasswordDataLayer = new ChangePasswordDataLayer();
            var result = changepasswordDataLayer.GetNewPassword(ResetPass, strCurrentPass, strNewPass);

            return (result);
        }
        private string GetSHA1(string password)
        {
            SHA1CryptoServiceProvider sha1Provider = new SHA1CryptoServiceProvider();
            sha1Provider.ComputeHash(ASCIIEncoding.ASCII.GetBytes(password));
            byte[] hashArray = sha1Provider.Hash;
            StringBuilder SB_Hexadecimal = new StringBuilder();
            foreach (byte passByte in hashArray)
            {
                SB_Hexadecimal.AppendFormat("{0:x2}", passByte);
            }
            return SB_Hexadecimal.ToString();
        }
        #endregion
    }
}

CIAB/Views/ChangePassword/ChangeUserPassword.cshtml
@model CIAB.Models.ResetPassword

@{
    ViewBag.Title = "ChangeUserPassword";
}
<script src='@Url.Content("~/Scripts/jquery.min.js")' type='text/javascript'></script>
<script src='@Url.Content("~/Scripts/jquery.validate.js")' type='text/javascript'></script>
<script src='@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")' type='text/javascript'></script>


<div id="about_top">
    <div class="container">
        <div class="row signup_login">
            <div class="col-md-6 col-md-offset-3 signup_left">

                <div class="header_wrap">
                    <h3>Change Password</h3>

                </div>


                <!-- Register Form Starts Here-->
                @using (Html.BeginForm("ChangeUserPassword", "ChangePassword", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        <label for="">Current Password <span class="req">*</span></label>
                        @Html.PasswordFor(p => p.CurrentPass, new { @class = "form-control" })
                        @*<input type="password" class="form-control" id="CurrentPass" name="CurrentPass" required placeholder="Enter your Current Password">*@
                        @Html.ValidationMessageFor(validation => validation.CurrentPass)

                        @if (ViewBag.ErrorMessage != null)
                        {
                            <span style="color:red">@ViewBag.ErrorMessage</span>
                        }

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">New Password <span class="req">*</span></label>
                        @Html.PasswordFor(p => p.NewPass, new { @class = "form-control" })
                        @*<input type="password" class="form-control" id="NewPass" name="NewPass" required placeholder="New Password">*@
                        <span id="helpBlock" class="help-block">5 characters minimum, no spaces, no special characters</span>
                        @Html.ValidationMessageFor(error => error.NewPass)
                    </div>
                    <div class="form-group">
                        <label for="Password">Confirm New Password <span class="req">*</span></label>
                        @Html.PasswordFor(p => p.ConfirmNewPassword, new { @class = "form-control" })
                        @*<input type="password" class="form-control" id="ConfirmNewPassword" name="ConfirmNewPassword" required placeholder="Confirm Password">*@
                        @Html.ValidationMessageFor(error => error.ConfirmNewPassword)
                       
                        @if (ViewBag.Error != null)
                        {
                            <span style="color:red">@ViewBag.Error</span>
                        }
                        
                        
                    </div>

                    <button type="submit" class="btn btn-default btn-block btn-cta">Change Password</button>
                }
                <!--Register Form Ends Here-->
            </div><!-- /about_header -->
        </div>
    </div>
</div>

CIAB/Views/ChangePassword/PasswordResetSuccess.cshtml
@{
    ViewBag.Title = "PasswordResetSuccess";
}


<div id="about_top">
    <div class="container">
        <div class="header_wrap">

            <h2>Successfully updated the Password.</h2>

           </div>
    </div>
</div>


            