CIAB/Controllers/OrderDetailsController.cs
using System;
using System.Data.SqlClient;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Data;
using CIAB.Models;


namespace CIAB.Controllers
{
    public class OrderDetailsController : BaseController
    {
        #region Methods
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult OrderDetail(string OrderNumber)
        {
            var orderDetailsPage = new OrderDetailsPage();
            try
            {
                SqlConnection CIABconnection = new SqlConnection(CIABconnectionString);
                SqlCommand CIABcommand = new SqlCommand();
                CIABconnection.Open();
                CIABcommand.CommandType = System.Data.CommandType.StoredProcedure;
                CIABcommand.Connection = CIABconnection;
                CIABcommand.CommandText = "sp_OrdersDetailPage";
                CIABcommand.Parameters.AddWithValue("@OrderID", OrderNumber);//pass order number to sql server
                SqlDataReader reader = CIABcommand.ExecuteReader();
                while (reader.Read())
                {
                    orderDetailsPage.OrderId = Convert.ToInt32(reader["OrderID"]);
                    orderDetailsPage.ProductName = reader["ProductName"].ToString();
                    orderDetailsPage.Email = reader["Email"].ToString();
                    orderDetailsPage.CompanyName = reader["CompanyName"].ToString();
                }
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "OrderDetail_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
            }
            return View(orderDetailsPage);
        }
        [HttpPost]
        public ActionResult OrderReport1(HttpPostedFileBase OrderReportFile1, int? orderNumber)
        {
            var viewModel = TempData["OrderDetail"];
            try
            {
                string strFileName = "File1";
                var orderDetails = new Models.OrderDetailsPage();
                if (OrderReportFile1 != null && OrderReportFile1.ContentLength > 0)// The Name of the Upload component is "OrderReportFile"
                {
                    orderDetails.FileName = Path.GetFileName(OrderReportFile1.FileName);//Get the File Name.
                    orderDetails.FileExtension = Path.GetExtension(orderDetails.FileName);//Get the File Extension for Validation.
                    if (orderDetails.FileExtension == ".PDF" || orderDetails.FileExtension == ".pdf")
                    {
                        byte[] orderReportFileToUpload = new byte[OrderReportFile1.ContentLength]; //declare byte array
                        string strBase64String = Convert.ToBase64String(orderReportFileToUpload, 0, orderReportFileToUpload.Length);
                        OrderReportFile1.InputStream.Read(orderReportFileToUpload, 0, OrderReportFile1.ContentLength);
                        SqlConnection CIABconnection = new SqlConnection(CIABconnectionString);
                        SqlCommand CIABcommand = new SqlCommand();
                        CIABconnection.Open();
                        CIABcommand.CommandType = System.Data.CommandType.StoredProcedure;
                        CIABcommand.Connection = CIABconnection;
                        CIABcommand.CommandText = "sp_StoreOrderReports";
                        CIABcommand.Parameters.AddWithValue("@fileName", SqlDbType.NVarChar).Value = strFileName;
                        CIABcommand.Parameters.AddWithValue("@OrderID", SqlDbType.Int).Value = orderNumber;//pass orderNumber to sql server
                        CIABcommand.Parameters.AddWithValue("@Data", SqlDbType.VarBinary).Value = orderReportFileToUpload;
                        CIABcommand.Parameters.AddWithValue("@ActualFileName", SqlDbType.NVarChar).Value = orderDetails.FileName;
                        SqlDataReader reader = CIABcommand.ExecuteReader();
                        ViewBag.UploadMessageFile1 = "File uploaded successfully";
                        return View("OrderDetail", viewModel);
                    }
                }
                ViewBag.UploadMessageFile1 = "Please Select a .PDF File";
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "OrderReport1_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
            }
            return View("OrderDetail", viewModel);
        }
        [HttpPost]
        public ActionResult OrderReport2(HttpPostedFileBase OrderReportFile2, int? orderNumber)
        {
            string strFileName = "File2";
            var viewModel = TempData["OrderDetail"];
            var orderDetails = new Models.OrderDetailsPage();
            try
            {
                if (OrderReportFile2 != null && OrderReportFile2.ContentLength > 0)// The Name of the Upload component is "OrderReportFile"
                {
                    orderDetails.FileName = Path.GetFileName(OrderReportFile2.FileName);//Get the File Name.
                    orderDetails.FileExtension = Path.GetExtension(orderDetails.FileName);//Get the File Extension for Validation.
                    if (orderDetails.FileExtension == ".PDF" || orderDetails.FileExtension == ".pdf")
                    {
                        byte[] orderReportFileToUpload = new byte[OrderReportFile2.ContentLength]; //declare byte array
                        OrderReportFile2.InputStream.Read(orderReportFileToUpload, 0, OrderReportFile2.ContentLength);
                        SqlConnection CIABconnection = new SqlConnection(CIABconnectionString);
                        SqlCommand CIABcommand = new SqlCommand();
                        CIABconnection.Open();
                        CIABcommand.CommandType = System.Data.CommandType.StoredProcedure;
                        CIABcommand.Connection = CIABconnection;
                        CIABcommand.CommandText = "sp_StoreOrderReports";
                        CIABcommand.Parameters.AddWithValue("@fileName", SqlDbType.NVarChar).Value = strFileName;
                        CIABcommand.Parameters.AddWithValue("@OrderID", SqlDbType.Int).Value = orderNumber;//pass orderNumber to sql server
                        CIABcommand.Parameters.AddWithValue("@Data", SqlDbType.VarBinary).Value = orderReportFileToUpload;
                        CIABcommand.Parameters.AddWithValue("@ActualFileName", SqlDbType.NVarChar).Value = orderDetails.FileName;
                        SqlDataReader reader = CIABcommand.ExecuteReader();
                        ViewBag.UploadMessageFile2 = "File uploaded successfully";
                        return View("OrderDetail", viewModel);
                    }
                }
                ViewBag.UploadMessageFile2 = "Please Select a .PDF File";
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "OrderReport2_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
            }
            return View("OrderDetail", viewModel);
        }
        [HttpPost]
        public ActionResult OrderReport3(HttpPostedFileBase OrderReportFile3, int? orderNumber)
        {
            string strFileName = "File3";
            var viewModel = TempData["OrderDetail"];
            var orderDetails = new OrderDetailsPage();
            try
            {
                if (OrderReportFile3 != null && OrderReportFile3.ContentLength > 0)// The Name of the Upload component is "OrderReportFile"
                {
                    orderDetails.FileName = Path.GetFileName(OrderReportFile3.FileName);//Get the File Name.
                    orderDetails.FileExtension = Path.GetExtension(orderDetails.FileName);//Get the File Extension for Validation.
                    if (orderDetails.FileExtension == ".PDF" || orderDetails.FileExtension == ".pdf")
                    {
                        byte[] orderReportFileToUpload = new byte[OrderReportFile3.ContentLength]; //declare byte array
                        OrderReportFile3.InputStream.Read(orderReportFileToUpload, 0, OrderReportFile3.ContentLength);
                        SqlConnection CIABconnection = new SqlConnection(CIABconnectionString);
                        SqlCommand CIABcommand = new SqlCommand();
                        CIABconnection.Open();
                        CIABcommand.CommandType = System.Data.CommandType.StoredProcedure;
                        CIABcommand.Connection = CIABconnection;
                        CIABcommand.CommandText = "sp_StoreOrderReports";
                        CIABcommand.Parameters.AddWithValue("@fileName", SqlDbType.NVarChar).Value = strFileName;
                        CIABcommand.Parameters.AddWithValue("@OrderID", SqlDbType.Int).Value = orderNumber;//pass orderNumber to sql server
                        CIABcommand.Parameters.AddWithValue("@Data", SqlDbType.VarBinary).Value = orderReportFileToUpload;
                        CIABcommand.Parameters.AddWithValue("@ActualFileName", SqlDbType.NVarChar).Value = orderDetails.FileName;
                        SqlDataReader reader = CIABcommand.ExecuteReader();
                        ViewBag.UploadMessageFile3 = "File uploaded successfully";
                        return View("OrderDetail", viewModel);
                    }
                }
                ViewBag.UploadMessageFile3 = "Please Select a .PDF File";
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "OrderReport3_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
            }
            return View("OrderDetail", viewModel);
        }
        public FileResult ShowDocument1(int? orderNumber, string FileName)
        {
            try
            {
                SqlConnection CIABconnection = new SqlConnection(CIABconnectionString);
                SqlCommand CIABcommand = new SqlCommand();
                CIABconnection.Open();

CIAB/Views/OrderDetails/OrderDetail.cshtml
@model CIAB.Models.OrderDetailsPage
@{
    ViewBag.Title = "OrderDetail";
    Layout = null;
}

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@Scripts.Render("~/bundles/modernizr")
@Styles.Render("~/Content/kendo/css")
@Scripts.Render("~/bundles/kendo")
@Styles.Render("~/Content/css")

@*<script src="~/Scripts/jquery-1.8.3.min.js"></script>
    <script src="~/Scripts/jquery.bxslider.js"></script>
    <script src="~/Scripts/jquery.royalslider.min.js"></script>*@
<script src="~/Scripts/kendo/kendo.web.min.js"></script>
<script src="~/Scripts/kendo.aspnetmvc.min.js"></script>
<script src="~/Scripts/kendo.all.min.js"></script>


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<link href="~/Content/colorbox.css" rel="stylesheet" />
<link href="~/Content/royalslider.css" rel="stylesheet" />
<link href="~/Content/skins/default/rs-default.css" rel="stylesheet" />
<link href="~/Content/custom.css" rel="stylesheet" />
<link href="~/Content/style.css" rel="stylesheet" />
@{Html.EnableClientValidation(true);}


<div class="modal-header">
    <h4>Purchase Request Details</h4>
</div>
<div class="modal-body" style="background-color:white; padding:40px 50px;">
    @{
        TempData["OrderDetail"] = Model;// pass the Model to controller
    }
    <div class="bg-info">
        <div class="form-horizontal admin_form">
            <div class="form-group">
                <p class="col-sm-3 admin_title">Request ID:</p>
                <div class="col-sm-9">
                    <p><strong>@Model.OrderId</strong></p>
                </div>
            </div>
            <div class="form-group">
                <p class="col-sm-3 admin_title">Email:</p>
                <div class="col-sm-9">
                    <p><strong>@Model.Email</strong></p>
                </div>
            </div>
            <div class="form-group">
                <p class="col-sm-3 admin_title">Company:</p>
                <div class="col-sm-9">
                    <p><strong>@Model.CompanyName</strong></p>
                </div>
            </div>
            <div class="form-group">
                <p class="col-sm-3 admin_title">Solutions:</p>
                <div class="col-sm-9">
                    <p><strong>@Model.ProductName</strong></p>
                </div>
            </div>


            <div class="form-group">
                <!--Upload File 1 Starts-->
                <div class="col-sm-offset-3 col-sm-9">
                    <span>Upload report:</span>
                    <div style="width:50%">
                        @using (Html.BeginForm("OrderReport1", "OrderDetails", new { orderNumber = @Model.OrderId }, FormMethod.Post))
                        {
                            @(Html.Kendo().Upload()
                               .Name("OrderReportFile1")
                               .Multiple(false)
                               .HtmlAttributes(new { accept = ".pdf, .PDF" })
                               .Messages(m => m.Select("Select .PDF file"))

                            )
                            <p>
                                <input type="submit" value="Upload Report 1" class="btn btn-danger" />
                            </p>
                        }
                      
                        <iframe src="@Url.Action("ShowDocument1", "OrderDetails", new {OrderNumber = @Model.OrderId, FileName = "File1" })" style="width:500px; height:500px;" frameborder="0"></iframe>


                        <span style="color:red">@ViewBag.UploadMessageFile1 </span>
                    </div>
                </div><!--Upload File 1 Ends-->




                <div class="form-group">
                    <!--Upload File 2 Starts-->
                    <div class="col-sm-offset-3 col-sm-9">
                        <span>Upload report:</span>
                        <div style="width:50%">
                            @using (Html.BeginForm("OrderReport2", "OrderDetails", new { orderNumber = @Model.OrderId }, FormMethod.Post, new { style = "50px;" }))
                            {
                                @(Html.Kendo().Upload()
                               .Name("OrderReportFile2")
                               .Multiple(false)
                               .HtmlAttributes(new { accept = ".pdf, .PDF" })
                               .Messages(m => m.Select("Select .PDF file"))
                                )
                                <p>
                                    <input type="submit" value="Upload Report 2" class="btn btn-danger" />
                                </p>
                                <iframe src="@Url.Action("ShowDocument2", "OrderDetails", new {OrderNumber = @Model.OrderId, FileName = "File2"})" style="width:500px; height:500px;" frameborder="0"></iframe>
                                <span style="color:red">@ViewBag.UploadMessageFile2 </span>
                            }
                        </div>
                    </div>
                </div> <!--Upload File 2 Ends-->




                <div class="form-group">
                    <!--Upload File 3 Starts-->
                    <div class="col-sm-offset-3 col-sm-9">
                        <span>Upload report:</span>
                        <div style="width:50%">
                            @using (Html.BeginForm("OrderReport3", "OrderDetails", new { orderNumber = @Model.OrderId }, FormMethod.Post))
                            {
                                @(Html.Kendo().Upload()
                               .Name("OrderReportFile3")
                               .Multiple(false)
                               .HtmlAttributes(new { accept = ".pdf, .PDF" })
                               .Messages(m => m.Select("Select .PDF file"))
                                )
                                <p>
                                    <input type="submit" value="Upload Report 3" class="btn btn-danger" />
                                </p>
                            }
                            <span style="color:red">@ViewBag.UploadMessageFile3</span>
                            <iframe src="@Url.Action("ShowDocument3", "OrderDetails", new {OrderNumber = @Model.OrderId, FileName = "File3" })" style="width:500px; height:500px;" frameborder="0"></iframe>

                        </div>
                    </div>
                </div>     <!--Upload File 3 Ends-->
            </div>
        </div></div></div>