CIAB/Models/UserPurchasesViewModel.cs
using System;
namespace CIAB.Models
{
    public class UserPurchasesViewModel
    {
        public int? OrderID { get; set; }
        public int UserId { get; set; }
        public int? Quantity { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? OrderNumber { get; set; }
        public DateTime? OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public string UserEmail { get; set; }
        public string UserCompany { get; set; }
        public string UserContactNumber { get; set; }
        public string ProductName { get; set; }
        public string FileName1 { get; set; }
        public string FileName2 { get; set; }
        public string FileName3 { get; set; }
    }
}

CIAB/Controllers/UserPurchasesController.cs
using CIAB.DataLayer;
using System;
using System.Web.Mvc;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace CIAB.Controllers
{
    public class UserPurchasesController : BaseController
    {
        #region Methods
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ViewUserOrders()
        {
            if (Convert.ToString(Session["UserName"]).ToLower() == null || Convert.ToString(Session["UserName"]).ToLower() == string.Empty)
            {
                return RedirectToAction("SignUpLogin", "Home");
            }
            try
            {
                var userPurchaseDL = new UserPurchasesDataLayer();
                var Result = userPurchaseDL.GetListOfUserOrders();
                return View(Result);
            }
            catch (Exception ex)
            {
                base.Logger.Error(ex, "ViewUserOrders_{0} | StackTrace: {1}", ex.Message, ex.StackTrace);
                return View();
            }
        }
        public FileResult DownloadReport(int? orderID, string File, string filename)
        {
            var userOrdersDL = new UserPurchasesDataLayer();
            byte[] pdfbytes =userOrdersDL.GetPDFFromDB(orderID, File);
            MemoryStream workStream = new MemoryStream();
            Document document = new Document();
            PdfWriter.GetInstance(document, workStream).CloseStream = false;
            byte[] byteInfo = pdfbytes;
            workStream.Write(byteInfo, 0, byteInfo.Length);
            workStream.Position = 0;
            Response.AppendHeader("Content-Disposition", "attachment; filename=" + filename);
            return new FileStreamResult(workStream, "application/pdf");
        }
        #endregion
    }
}

CIAB/Views/UserPurchases/ViewUserOrders.cshtml
@model IEnumerable<CIAB.Models.UserPurchasesViewModel>

<html>
<head>
    <meta name="description" content="KPMG cybersecurity cyberinabox" />
    <meta name="keywords" content="KPMG, contact, address, singapore, cybersecurity" />
    <title>User Purchases</title>
    <script src="~/Scripts/jszip.min.js"></script>
</head>
<body>

    <div id="sub_content" style="padding:130px">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="bs-example" data-example-id="striped-table" style="background: #fff; padding: 36px 30px 1px 21px;">

                        @(Html.Kendo().Grid(Model).Name("OrdersGrid").Columns(columns =>
                            {
                                columns.Bound(p => p.OrderID).Title("Request ID");
                                columns.Bound(p => p.ProductName).Title("Product Name");
                                columns.Bound(p => p.OrderDate).Title("Date").Format("{0:MMMM dd, yyyy}");
                                columns.Bound(p => p.UserEmail).Title("Email");
                                columns.Bound(p => p.UserCompany).Title("Company");
                                columns.Bound(p => p.UserContactNumber).Title("Contact Number");
                                columns.Bound(p => p.OrderStatus).Title("Status");
                                columns.Bound(p => p.OrderID).ClientTemplate(
                                        "<ul> " +
                                            @"     <a href='" + @Url.Action("DownloadReport", "UserPurchases") + "?orderID= ${OrderID} &File=File1 &fileName=${FileName1}'> ${FileName1} </a>" +
                                            @"</br><a href='" + @Url.Action("DownloadReport", "UserPurchases") + "?orderID= ${OrderID} &File=File2 &fileName=${FileName2}'> ${FileName2} </a>" +
                                            @"</br><a href='" + @Url.Action("DownloadReport", "UserPurchases") + "?orderID= ${OrderID} &File=File3 &fileName=${FileName3}'> ${FileName3} </a>" +
                                            "</ul>"
                                    ).Width("100%");
                            })

        .DataSource(dataSource => dataSource
        .Ajax()
        .Model(model =>
        {
            model.Id(config => config.OrderID);
        })
        .PageSize(10)
        .ServerOperation(false)
        .Read(read => read.Action("AdminView", "Admin"))
        )
        .Reorderable(reorder => reorder.Columns(true))
        .Resizable(resize => resize.Columns(true))
        .Pageable()
        .Sortable()
        .ColumnMenu()
        //.HtmlAttributes(new { style = "height:450px; width: 1100px" })
        )
                    </div>

                </div>
            </div>
        </div>
    </div><!-- /sub_header -->
    <script type="text/javascript">
        function error_handler(e) {
            if (e.errors) {
                var message = "Errors:\n";
                $.each(e.errors, function (key, value) {
                    if ('errors' in value) {
                        $.each(value.errors, function () {
                            message += this + "\n";
                        });
                    }
                });
                //alert(message);
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $("#myBtn").click(function () {
                $("#myModal").modal();
            });
        });
    </script>
</body>
</html>